kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  labels:
    node-type: control-node
- role: worker
  labels:
    node-type: worker
- role: worker
  labels:
    node-type: worker
- role: worker
  labels:
    node-type: worker
