prometheusOperator:
  namespaces:
    releaseNamespace: true
    additional:
      - kube-system
      - monitoring

prometheus:
  enabled: true
  serviceMonitorSelector:
    matchLabels:
      prometheus: true
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelectorNilUsesHelmValues: true

grafana:
  adminUser: test
  adminPassword: test1234
