replicaCount: 3
nodeSelector:
  node-type: worker
zookeeper:
  enabled: false
kraft:
  enabled: true
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
  clusterId: MjM4YTEyMzRmZjFkMTFlZG
auth:
  clientProtocol: plaintext
  externalClientProtocol: plaintext
allowPlaintextListener: true
serviceAccount:
  create: true
rbac:
  create: false
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
    labels:
      app: kafka-jmx
      release: kube-prometheus-stack
  serviceMonitor:
    enabled: true
    labels:
      app: kafka
      release: kube-prometheus-stack
