prometheusOperator:
  namespaces:
    releaseNamespace: true
    additional:
      - kube-system
      - monitoring
      - my-namespace

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        release: my-own-release
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: name
          operator: In
          values:
            - monitoring
            - my-namespace
            - kube-system

grafana:
  adminUser: test
  adminPassword: test1234
